---
title: Ash Kara
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    location: 
author: Ash Kara
email: ash@ashkaratalentconsultant.com
description: We are a talent search company with over a decade's experience in digital
  marketing, products, and branding space.
minima:
  date_format: "%b %-d, %Y"
markdown: kramdown
markdown_ext: markdown, mkdown, mkdn, mkd, md
kramdown:
  parse_block_html: true
